version: "3.8"

networks:
  customnetwork:
    external: true
    name: minecraft-stack

services:
  minecraft-(CHANGETHIS):
    restart: always
    image: minecraft-(CHANGETHIS)
    build: ./minecraft-docker
    command: ["java", "-Xmx2048M", "-jar", "server.jar", "true"]
    networks:
      customnetwork:
        ipv4_address: 192.168.16.(CHANGETHIS)
    volumes:
      - "./data:/root/minecraft"
    ports:
      - "25565:25565"
      - "8001:8001" # RCON (REMOTE CONSOLE)
